[package]
name = "wincredentials-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.21.1"
bindings = { path = "bindings" }
widestring = "0.4.3"